### ISSUE TITLE
Allow passing babel config through regular Jest config?

### ISSUE THREAD

**Issue by tunnckoCore** [rickhanlonii/jest-runner-babel#1]
Hey again, Rick!

Just noticed that you use `cosmiconfig` to get the babel config from `jest-runner-babel` config, which... isn't great experience in my opinion. Also blocks if you want to provide "zero config" experience. For example building a tool that wraps the things, but also allow your end users to be able to use their configs if they need.

Currently, this runner forces end-users to have a `jest-runner-babel` config.

_Same as https://github.com/jest-community/jest-runner-eslint/issues/66_

**Comment by tunnckoCore** [comment]
Temp solution https://github.com/jest-community/jest-runner-eslint/issues/66#issuecomment-502500668 but this should land in runners you want to use.

**Comment by tunnckoCore** [comment]
Why in `config.haste`? Glad you asked. You can actually put whatever name you want in your jest config file (`module.exports = { foobar: 123 }`), but it won't appear in the jest runner (e.g. `{ config }`, the `config.foobar` won't exist), but `haste` appears, always.

**Comment by rickhanlonii** [comment]
Hey @tunnckoCore, thanks for the suggestion! I'd love for both libraries to work with a jest config, but unfortunately we have to do it this way until jest supports runner options like it does for reporters :<

**Comment by rickhanlonii** [comment]
Happy to continue the discussion and re-open after Jest adds support!

**Comment by tunnckoCore** [comment]
Yea, no problem. :) I have forked for that reason until then. It's a temporary solution that doesn't bother me.
